# orquestador de servicios

# Se encargará de levantar los servicios.
# También crea automáticamente la bridge dónde estarán los servicios
version: '3.8'

services:
  nginx:
    build: ./requirements/nginx # Ruta dockerfile NGINX
    container_name: nginx
    networks:
      - inception
    ports:
      - "443:443"
    restart: always # Restart: Policy "Apuntes.md, line 31"

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - .env # Include environments.
    networks:
      - inception
    restart: always

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    secrets: # Aqui añadimos los secretos de compose
      - db_password
      - db_root_password
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE} # Name of environments.
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets_db_root_password
    networks:
      - inception
    restart: always

# Aqui estoy definiendo el tipo de network que usaremos, en este caso
# bridge.
networks:
  inception:
    driver : bridge

# Aqui definiré los secrets, que será donde guardaré las
# contraseñas y variables de entorno confidenciales

secrets:
  db_password:
    file: ./db_password.txt
  db_root_password:
    file: ./db_root_password.txt
