server {
	listen 443 ssl;      //  IPv4
	listen [::]:443 ssl; // IPv6


	server_name dacastil.42.fr;

	# RUTAS DE CERTIFICADOS
	ssl_certificate /
	ssl_certificate_key /

	# PROTOCOLO TLS 1.2 o 1.3 PARA HTTPS
	ssl_protocols TLSv1.2 TLSv1.3;
}
